In [47]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler


In [48]:
x_train = pd.read_pickle('../Data/train_test_data/x_train.pkl')
x_test = pd.read_pickle('../Data/train_test_data/x_test.pkl')
y_train= pd.read_pickle('../Data/train_test_data/y_train.pkl')
y_test= pd.read_pickle('../Data/train_test_data/y_test.pkl')



In [49]:
y_train = y_train.reset_index(drop=True)


In [50]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)


In [51]:
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score

# c_values=[0.01,0.1,1,10,100]
# for c in c_values:
model = LogisticRegression(
          C=0.1,
        penalty="l2",
        solver="lbfgs",
        max_iter=1000
).fit(x_train,y_train)
y_pred = model.predict(x_test)



c:\Users\SHUBHAM KUMAR\Mtech\AIML-M.TECH\GENAI\Ai_hedge_fund\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(


In [52]:
print(model.n_iter_)

[236]


In [53]:
predicted_probability = model.predict_proba(x_test)
from sklearn.metrics import roc_auc_score

proba = model.predict_proba(x_test)[:, 1]


In [54]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

print()
print(f"accuracy: {accuracy_score(y_test, y_pred)}")
print(f"precision (macro): {precision_score(y_test, y_pred, average='macro')}")
print(f"recall (macro): {recall_score(y_test, y_pred, average='macro')}")
print(f"confusion_matrix:\n{confusion_matrix(y_test, y_pred)}")
print("\nclassification report:")
print(classification_report(y_test, y_pred, zero_division=0))



accuracy: 0.48
precision (macro): 0.16
recall (macro): 0.3333333333333333
confusion_matrix:
[[  0 156   0]
 [  0 228   0]
 [  0  91   0]]

classification report:
              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00       156
         0.0       0.48      1.00      0.65       228
         1.0       0.00      0.00      0.00        91

    accuracy                           0.48       475
   macro avg       0.16      0.33      0.22       475
weighted avg       0.23      0.48      0.31       475



c:\Users\SHUBHAM KUMAR\Mtech\AIML-M.TECH\GENAI\Ai_hedge_fund\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [55]:
metric_scores={
    'Model':'LogisticRegression',
    'Accuracy_score':accuracy,
        'Precision_score':precision,
        'ROC_AUC_score':  roc_auc
}

NameError: name 'precision' is not defined

In [ ]:
result_data = pd.DataFrame(
   [metric_scores]
)

In [ ]:
result_data.to_csv('../models/models_performance_tracker.csv')