In [64]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
import pandas as pd

In [65]:
x_train = pd.read_pickle('../Data/train_test_data/x_train.pkl')
x_test = pd.read_pickle('../Data/train_test_data/x_test.pkl')
y_train = pd.read_pickle('../Data/train_test_data/y_train.pkl')
y_test = pd.read_pickle('../Data/train_test_data/y_test.pkl')


In [66]:

rnf = RandomForestClassifier(
    n_estimators=500,
    max_depth=8,              # shallow trees — noisy financial data overfits fast at high depth
    min_samples_leaf=20,      # forces leaves to have enough samples, reduces overfit to noise
    class_weight='balanced_subsample',  # <-- key fix: penalizes majority-class predictions
    random_state=42,
    n_jobs=-1
)
rnf.fit(x_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",500
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",8
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",20
,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel. :meth:`fit`, :meth:`predict`,:meth:`decision_path` and :meth:`apply` are all parallelized over thetrees. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`context. ``-1`` means using all processors. See :term:`Glossary<n_jobs>` for more details.",-1
,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"class_weight class_weight: {""balanced"", ""balanced_subsample""}, dict or list of dicts, default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one. Formulti-output problems, a list of dicts can be provided in the sameorder as the columns of y.Note that for multioutput (including multilabel) weights should bedefined for each class of every column in its own dict. For example,for four-class multilabel classification weights should be[{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of[{1:1}, {2:5}, {3:1}, {4:1}].The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``The ""balanced_subsample"" mode is the same as ""balanced"" except thatweights are computed based on the bootstrap sample for every treegrown.For multi-output, the weights of each column of y will be multiplied.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified.",'balanced_subsample'
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider

In [67]:
y_pred = rnf.predict(x_test)

In [68]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

print()
print(f"accuracy: {accuracy_score(y_test, y_pred)}")
print(f"precision (macro): {precision_score(y_test, y_pred, average='macro')}")
print(f"recall (macro): {recall_score(y_test, y_pred, average='macro')}")
print(f"confusion_matrix:\n{confusion_matrix(y_test, y_pred)}")
print("\nclassification report:")
print(classification_report(y_test, y_pred, zero_division=0))



accuracy: 0.48
precision (macro): 0.16
recall (macro): 0.3333333333333333
confusion_matrix:
[[  0 156   0]
 [  0 228   0]
 [  0  91   0]]

classification report:
              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00       156
         0.0       0.48      1.00      0.65       228
         1.0       0.00      0.00      0.00        91

    accuracy                           0.48       475
   macro avg       0.16      0.33      0.22       475
weighted avg       0.23      0.48      0.31       475



c:\Users\SHUBHAM KUMAR\Mtech\AIML-M.TECH\GENAI\Ai_hedge_fund\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [69]:
print("Train Accuracy:", rnf.score(x_train, y_train))
print("Test Accuracy:", rnf.score(x_test, y_test))

Train Accuracy: 0.7221929362150764
Test Accuracy: 0.48


In [70]:
importance = pd.DataFrame({
    "Feature": x_train.columns,
    "Importance": rnf.feature_importances_
}).sort_values("Importance", ascending=False)

print(importance.head(15))

               Feature  Importance
42  rolling_volatility    0.051550
44        Volume_MA_20    0.044445
46          wilder_atr    0.035512
17             EMA_200    0.033488
31                 OBV    0.032074
29                 ATR    0.031246
43                RVOL    0.030589
30                VWAP    0.029915
9         sma_5-sma_20    0.029816
23           histogram    0.029354
19              RSI_14    0.024573
8         Close-sma-50    0.023699
7               sma-50    0.023066
20              RSI_21    0.021516
16              EMA_50    0.021360


In [71]:
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

Label
 0.0    0.448603
-1.0    0.347391
 1.0    0.204006
Name: proportion, dtype: float64
Label
 0.0    0.480000
-1.0    0.328421
 1.0    0.191579
Name: proportion, dtype: float64


In [72]:
print(x_train.isna().sum().sort_values(ascending=False).head(10))

Price
Close           0
High            0
Low             0
Open            0
Volume          0
sma-5           0
sma-20          0
sma-50          0
Close-sma-50    0
sma_5-sma_20    0
dtype: int64


In [73]:
print(x_train.shape)
print(x_test.shape)

(1897, 49)
(475, 49)


In [74]:
# does the model even distinguish classes probabilistically?
probs = rnf.predict_proba(x_test)
import pandas as pd
print(pd.DataFrame(probs, columns=rnf.classes_).describe())

             -1.0         0.0         1.0
count  475.000000  475.000000  475.000000
mean     0.268894    0.614335    0.116771
std      0.027862    0.057259    0.040527
min      0.210213    0.443840    0.042736
25%      0.251173    0.584080    0.090013
50%      0.264599    0.613005    0.116621
75%      0.281464    0.650695    0.143929
max      0.369627    0.728714    0.232521
